### ISSUE TITLE
BND2 2.0.0.AppImage 运行报js错误

### ISSUE THREAD

**Issue by kekekekekeshi** [b3log/baidu-netdisk-downloaderx#48]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 描述问题
Uncaught Exception:
Error: EEXIST: file already exists, mkdir '/home/snowing/.bnd2'
    at Object.fs.mkdirSync (fs.js:885:18)
    at netRequest (/tmp/.mount_BND2 24vIDsm/resources/app.asar/src/utils.js:152:16)
    at IncomingMessage.response.on (/tmp/.mount_BND2 24vIDsm/resources/app.asar/src/utils.js:16:7)
    at emitOne (events.js:116:13)
    at IncomingMessage.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at IncomingMessage.Readable.push (_stream_readable.js:208:10)
    at IncomingMessage._pushInternalData (/tmp/.mount_BND2 24vIDsm/resources/electron.asar/browser/api/net.js:74:30)
    at URLRequest.IncomingMessage.urlRequest.on (/tmp/.mount_BND2 24vIDsm/resources/electron.asar/browser/api/net.js:27:12)

### 重现步骤

请描述如何重现这个问题：运行BND2 2.0.0.AppImage时出问题 

2. Click on '...'
3. Scroll down to '...'

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 截屏或录像

如果可能，请尽量附加截图或录像来描述你遇到的问题。

### 桌面端环境

- OS: [e.g. windows, mac, linux]

### 移动端环境

- Device: [e.g. iPhone8]
- OS: [e.g. iOS12]

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by 88250** [comment]
如果是自己编译的话请检查 bnd2 内核二进制是否编译成功。

**Comment by kekekekekeshi** [comment]
第一次没成功，第二次成功了。

**Comment by 88250** [comment]
如果失败那次的编译日志还在的话请上传，谢谢。

**Comment by kekekekekeshi** [comment]
> 如果失败那次的编译日志还在的话请上传，谢谢。

Downloading SHASUMS256.txt
Error: read ECONNRESET
/home/snowing/下载/baidu-netdisk-downloaderx-master/bnd2/electron/node_modules/electron/install.js:54
  throw err
  ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@2.0.8 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@2.0.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/snowing/.npm/_logs/2019-07-25T09_44_11_488Z-debug.log

**Comment by kekekekekeshi** [comment]
[2019-07-25T09_44_11_488Z-debug.log](https://github.com/b3log/baidu-netdisk-downloaderx/files/3430950/2019-07-25T09_44_11_488Z-debug.log)


> 如果失败那次的编译日志还在的话请上传，谢谢。

[2019-07-25T09_44_11_488Z-debug.log](https://github.com/b3log/baidu-netdisk-downloaderx/files/3430953/2019-07-25T09_44_11_488Z-debug.log)
这是日志文件

**Comment by 88250** [comment]
@kekekekekeshi 感谢反馈 ❤️

**Comment by kekekekekeshi** [comment]
> @kekekekekeshi 感谢反馈

不用客气

**Comment by Vanessa219** [comment]
后面这个日志看上去 npm 安装 electron 时错误，重新安装即可。

但是第一次的日志是 EEXIST: file already exists, mkdir '/home/snowing/.bnd2' 这个错误，可以详细说一下这个错误的重现步骤么？
