### ISSUE TITLE
bnd1--mac运行异常

### ISSUE THREAD

**Issue by hhhaiai** [b3log/baidu-netdisk-downloaderx#74]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 描述问题

```
2019-08-20 12:57:08.047 bnd[35375:6018586] *** Assertion failure in +[NSUndoManager _endTopLevelGroupings], /BuildRoot/Library/Caches/com.apple.xbs/Sources/Foundation/Foundation-1575.12/Foundation/Misc.subproj/NSUndoManager.m:361
2019-08-20 12:57:08.048 bnd[35375:6018586] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '+[NSUndoManager(NSInternal) _endTopLevelGroupings] is only safe to invoke on the main thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff3ea8dcfd __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff69137a17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff3eaa8a1a +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fff40d47c85 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   Foundation                          0x00007fff40c7acfa +[NSUndoManager(NSPrivate) _endTopLevelGroupings] + 473
	5   AppKit                              0x00007fff3c055915 -[NSApplication run] + 916
	6   bnd                                 0x00000000043f919b uiMain + 43
	7   bnd                                 0x0000000004056ba0 runtime.asmcgocall + 112
)
libc++abi.dylib: terminating with uncaught exception of type NSException
SIGABRT: abort
PC=0x7fff6aa402c6 m=7 sigcode=0
signal arrived during cgo execution

goroutine 39 [syscall, locked to thread]:
runtime.cgocall(0x43dc2a0, 0xc42045bf80, 0xc420164168)
	/usr/local/go/src/runtime/cgocall.go:128 +0x64 fp=0xc42045bf50 sp=0xc42045bf18 pc=0x4004354
github.com/b3log/bnd/vendor/github.com/andlabs/ui._Cfunc_uiMain()
	_cgo_gotypes.go:1784 +0x41 fp=0xc42045bf80 sp=0xc42045bf50 pc=0x40e4861
github.com/b3log/bnd/vendor/github.com/andlabs/ui.start(0xc42057a180, 0xc4205741b0)
	/Users/Vanessa/Work/Code/GoGoGo/src/github.com/b3log/bnd/vendor/github.com/andlabs/ui/main.go:56 +0x10e fp=0xc42045bfd0 sp=0xc42045bf80 pc=0x40e9c9e
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc42045bfd8 sp=0xc42045bfd0 pc=0x4057eb1
created by github.com/b3log/bnd/vendor/github.com/andlabs/ui.Main
	/Users/Vanessa/Work/Code/GoGoGo/src/github.com/b3log/bnd/vendor/github.com/andlabs/ui/main.go:36 +0x66

goroutine 1 [chan receive, locked to thread]:
github.com/b3log/bnd/vendor/github.com/andlabs/ui.Main(0xc4205741b0, 0xc4205741b0, 0x60)
	/Users/Vanessa/Work/Code/GoGoGo/src/github.com/b3log/bnd/vendor/github.com/andlabs/ui/main.go:37 +0x86
main.init.0()
	/Users/Vanessa/Work/Code/GoGoGo/src/github.com/b3log/bnd/main.go:37 +0x381

goroutine 7 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0xa7
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 37 [syscall]:
net._C2func_getaddrinfo(0xc420588000, 0x0, 0xc420574150, 0xc420582010, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:92 +0x55
net.cgoLookupIPCNAME.func1(0xc420588000, 0x0, 0xc420574150, 0xc420582010, 0x11, 0x11, 0xc42057e000)
	/usr/local/go/src/net/cgo_unix.go:149 +0x13b
net.cgoLookupIPCNAME(0xc420526c60, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/cgo_unix.go:149 +0x174
net.cgoIPLookup(0xc4205762a0, 0xc420526c60, 0x10)
	/usr/local/go/src/net/cgo_unix.go:201 +0x4d
created by net.cgoLookupIP
	/usr/local/go/src/net/cgo_unix.go:211 +0xaf

rax    0x0
rbx    0x700005391000
rcx    0x70000538f4d8
rdx    0x0
rdi    0x1c03
rsi    0x6
rbp    0x70000538f510
rsp    0x70000538f4d8
r8     0x70000538f3a0
r9     0x70000538f570
r10    0x0
r11    0x206
r12    0x1c03
r13    0x3000000008
r14    0x6
r15    0x2d
rip    0x7fff6aa402c6
rflags 0x206
cs     0x7
fs     0x0
gs     0x0

[进程已完成]


```

### 重现步骤

请描述如何重现这个问题：

1. 命令行运行、点击运行 直接报错

### 桌面端环境

- OS:  mac  10.14.5
- Version 4.0.0

**Comment by 88250** [comment]
这个问题暂时无法解决，可尝试多次重启。
